version: 2
jobs: 
 build:
  working-directory: ~/HacktoberfestStats
  docker:
    - image: circleci/node:8.12.0
  steps:
    - checkout
    - run:
        name: Update NPM
        command: 'sudo npm install -g npm@latest'
    - restore_cache: # special step to restore the dependency cache 
       key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Install NPM dependencies
        command: 'npm install package.json'
    - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
    - run:
        name: Testing HacktoberFest Stats!
        command: 'npm test'
    
